services:
  db:
    image: postgres:16
    container_name: atena_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: atena_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5435:5432'
    networks:
      - atena_net

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: atena_web
  #   command: gunicorn setup.wsgi:application --bind 0.0.0.0:8334
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8334:8334'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - atena_net

volumes:
  postgres_data:

networks:
  atena_net:
    driver: bridge
