services:
  db:
    image: postgres:16
    container_name: atena_db
    environment:
      POSTGRES_DB: atena_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - atena_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: atena_api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    ports:
      - '8001:8001'
    depends_on:
      - db
    networks:
      - atena_net
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: atena_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_PORT: 5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: atena_frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - '8000:8000'
    depends_on:
      - api
    networks:
      - atena_net
    environment:
      API_URL: http://api:8001/api
      API_URL_TOKEN: http://api:8001

volumes:
  postgres_data:

networks:
  atena_net:
    driver: bridge
