services:
  db:
    image: postgres:16
    container_name: atena_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: atena_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5435:5432'
    networks:
      - atena_net

  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/api/Dockerfile
  #   container_name: atena_api
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - '8001:8000'
  #   depends_on:
  #     - db
  #   networks:
  #     - atena_net
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_NAME: atena_db
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: admin
  #     DATABASE_PORT: 5435

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/frontend/Dockerfile
  #   container_name: atena_frontend
  #   env_file:
  #     - .env.frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - api
  #   networks:
  #     - atena_net

volumes:
  postgres_data:

networks:
  atena_net:
    driver: bridge
