# Generated by Django 5.2.6 on 2025-09-26 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GERENTE", "Gerente"),
                            ("PROFESSOR", "Professor"),
                            ("ALUNO", "Aluno"),
                        ],
                        default="ALUNO",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
